#!/usr/bin/env python3
"""Build chartLayouts.js from chart type classes."""

import os
import sys
import plotly.io as pio

# Add parent directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from Daily import DailySCC
from Weekly import WeeklySCC
from Monthly import MonthlySCC
from Yearly import YearlySCC
from FrequencyCollections import FrequencyCollectionsSCC

# Output path
OUTPUT_PATH = '../../static/SCC/util/chartLayouts.js'

# Chart configurations: (name, class, kwargs)
CHARTS = [
    ('Daily', DailySCC, {'xmax': 280, 'chart_window_in_days': 140}),
    ('Weekly', WeeklySCC, {'xmax': 200, 'chart_window_in_weeks': 100}),
    ('Monthly', MonthlySCC, {'xmax': 240, 'chart_window_in_months': 120}),
    ('Yearly', YearlySCC, {'xmax': 200, 'chart_window_in_years': 100}),
    ('FrequencyCollections', FrequencyCollectionsSCC, {'num_columns': 10, 'points_per_column': 7}),
]


def build():
    templates = {}

    for name, cls, kwargs in CHARTS:
        templates[name] = {}
        for minute_type in [True, False]:
            variant = 'minute' if minute_type else 'count'
            chart = cls(minute_type=minute_type, **kwargs)
            fig = chart.get_plot(to_json=False)
            # Remove Plotly's default template to reduce file size and avoid interference
            fig.layout.template = None
            # Use plotly.io.to_json with engine='json' to avoid binary encoding
            templates[name][variant] = pio.to_json(fig, engine='json')
            print(f'  {name}.{variant}')

    # Write JS file
    output_path = os.path.join(os.path.dirname(__file__), OUTPUT_PATH)
    with open(output_path, 'w') as f:
        f.write('// Chart layout templates - all chart types combined\n')
        f.write('// Generated by build_layouts.py\n\n')
        f.write('const TEMPLATES = {\n')

        for i, name in enumerate(templates):
            f.write(f'    {name}: {{\n')
            f.write(f'        minute: {templates[name]["minute"]},\n')
            f.write(f'        count: {templates[name]["count"]}\n')
            f.write('    }')
            f.write(',\n' if i < len(templates) - 1 else '\n')

        f.write('};\n\n')
        f.write('function getTemplate(chartType, isMinute) {\n')
        f.write('    const variant = isMinute ? "minute" : "count";\n')
        f.write('    return JSON.parse(JSON.stringify(TEMPLATES[chartType][variant]));\n')
        f.write('}\n\n')
        f.write('export { TEMPLATES, getTemplate };\n')

    print(f'\nWrote: {output_path}')


if __name__ == '__main__':
    print('Building chartLayouts.js...')
    build()
